### ISSUE TITLE
Getting an exception "Array to string conversion" while pushing the docker image

### ISSUE THREAD

**Issue by SadeeshKumarMN** [axelerant/db-docker#14]
**Problem Statement:** 
After upgrade with PHP 7.4.16 version, when execute the script "composer db-docker -vvv --db-file=<<name of the db file>>" getting the following error while the step belongs to pushing the image

Successfully built f1e2e1eaebff
Successfully tagged registry.gitorious.xyz/sadeesh.kumar/cypress-drupal-gitlab/db:latest
Pushing image...
Running 'docker push registry.gitorious.xyz/sadeesh.kumar/cypress-drupal-gitlab/db:latest'
The push refers to repository [registry.gitorious.xyz/sadeesh.kumar/cypress-drupal-gitlab/db]
d45ef4d23ff4: Preparing
5e1acc5de2f2: Preparing
d7bba8e97cf6: Preparing
65459a7deb12: Preparing
1209a4c70afb: Preparing
8d8baa5330f5: Preparing
1e6b37d2d789: Preparing
734cf8eb2019: Preparing
f6462d756f99: Preparing
6eee67373895: Preparing
2fad4a7427e4: Preparing
8d8baa5330f5: Waiting
1e6b37d2d789: Waiting
734cf8eb2019: Waiting
f6462d756f99: Waiting
6eee67373895: Waiting
2fad4a7427e4: Waiting
**Command returned exit code '1'
[ErrorException]            
Array to string conversion**

**Other Details:**
Composer Version:2.0.11
Drupal Version: 8.9.6

**ExceptionTrace:**
() at phar:///usr/local/bin/composer/vendor/symfony/process/Exception/ProcessFailedException.php:35
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 sprintf() at phar:///usr/local/bin/composer/vendor/symfony/process/Exception/ProcessFailedException.php:35
 Symfony\Component\Process\Exception\ProcessFailedException->__construct() at /Users/sadeeshkumarmn/Desktop/code/cypress-drupal-ci/cypress-drupal-gitlab/vendor/axelerant/db-docker/src/DbDockerCommand.php:285
 Axelerant\DbDocker\DbDockerCommand->execCmd() at /Users/sadeeshkumarmn/Desktop/code/cypress-drupal-ci/cypress-drupal-gitlab/vendor/axelerant/db-docker/src/DbDockerCommand.php:90
 Axelerant\DbDocker\DbDockerCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:63
 require() at /usr/local/bin/composer:24
 

**Project Repo:**
https://gitorious.xyz/sadeesh.kumar/cypress-drupal-gitlab

**Comment by hussainweb** [comment]
@SadeeshKumarMN, can you run just the command and see what's the error you get at the end?

```
docker push registry.gitorious.xyz/sadeesh.kumar/cypress-drupal-gitlab/db:latest
```

I suspect the problem is that Docker repository is not configured on that path. But the command above should give you a better error message.

The exception "Array to string conversion" is not related to the error you are facing. It is happening because the command failed and it could not generate a meaningful error message. I will fix that anyway but that will not fix your problem.

**Comment by SadeeshKumarMN** [comment]
@hussainweb Thank you. While executing this, I'm getting "denied: access forbidden" and seems permission issue

The push refers to repository [registry.gitorious.xyz/sadeesh.kumar/cypress-drupal-gitlab/db]
d45ef4d23ff4: Preparing 
5e1acc5de2f2: Preparing 
d7bba8e97cf6: Preparing 
65459a7deb12: Preparing 
1209a4c70afb: Preparing 
8d8baa5330f5: Waiting 
1e6b37d2d789: Waiting 
734cf8eb2019: Waiting 
f6462d756f99: Waiting 
6eee67373895: Waiting 
2fad4a7427e4: Waiting 
**denied: access forbidden**

**Comment by hussainweb** [comment]
Thanks for confirming @SadeeshKumarMN. The problem is not with db-docker here, but we should definitely fix the issue with the exception hiding the actual error.
