### ISSUE TITLE
Add support for Github

### ISSUE THREAD

**Issue by skippednote** [axelerant/db-docker#22]
- [x] Support Github URLs
- [ ] Support HTTPS URLs besides the currently supported ssh ones

**Comment by subhojit-axl** [comment]
Also, IMO there should be a provision to pass the remote host while building the image. Let's say, the user keeps multiple GitHub accounts, and there is a different private key associated with the account. The SSH config in the user's machine might look something like this:

```
Host github-personal.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa_personal

Host github-work.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa_work
```

The db-docker will look for only the selected ones, and it will fail. Therefore, user should have the ability to pass the host name, and therefore controlling which GitHub account is being referred.

**Comment by hussainweb** [comment]
@subhojit-axl, this applies not only to Github but generally too. Would you mind creating an issue for it?

**Comment by subhojit-axl** [comment]
Issue created #24
