### ISSUE TITLE
Definition of "plugins" is not clear in the README

### ISSUE THREAD

**Issue by subhojit777** [axelerant/db-docker#4]
### Motivation:

While going through the README I understood two usages of the word "plugin".

1. "plugin" as in Composer plugin - I understood this while reading the intro https://github.com/axelerant/db-docker#introduction. I think the user would understand it correctly.
1. "plugin" as in? - I read this `--no-plugins Whether to disable plugins.` in the usage https://github.com/axelerant/db-docker#usage, and this one I am not clear about which "plugin" it is referring to.

Maybe, the README should state more clearly what kind of "plugin" it refers in the usage section.

**Comment by subhojit777** [comment]
FYI @hussainweb

**Comment by hussainweb** [comment]
@subhojit777, thanks for this. The usage is generated by running `composer db-docker --help` and composer outputs the help for `--no-plugins`. I agree it is not helpful here. Can you create a PR to remove that line? And let's think about what we can do in the long-term.

**Comment by subhojit777** [comment]
What are we planning in long term?

**Comment by subhojit777** [comment]
> What are we planning for long term?

Asked because I saw your commit regarding the warning https://github.com/axelerant/db-docker/commit/3ef9ee68e9e819e47fcfebc6b7fe81fc8b15dd7a#diff-04c6e90faac2675aa89e2176d2eec7d8 So, I thought you want to keep the option in the README.

**Comment by hussainweb** [comment]
@subhojit777, I'm on the fence about this. The reason to keep it as-is is to make it easier to add any new options later on. I typically copy-paste the output of `--help` and put it in the README. There is a chance this option will get reintroduced later.

Whereas if we leave a warning, the warning will remain and guide people in case someone thinks of running this along with `--no-plugins`.

**Comment by subhojit777** [comment]
I agree with your point. Closing this.
